Listener.o: Listener.c Listener.h
Message.o: Message.c Message.h Listener.h
TestModuleTraduction.o: TestModuleTraduction.c TestModuleTraduction.h \
 Listener.h Message.h
main.o: main.c Listener.h Message.h
moduleTraduction.o: moduleTraduction.c Listener.h Message.h
